server:
  port: 9093
spring:
  profiles:
    active: qa
  application:
    name: nice-customer-microservice
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/bookings
    username: root
    password: root
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    show-sql: true
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.hbm2ddl.auto: create
application:
  cars-microservice:
    host: http://localhost
    port: 9092
    get-cars: /cars
  customers-microservice:
    host: http://localhost
    port: 9091
    get-customers: /cusomers
  booking-microservice:
    host: http://localhost
    port: 9093
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:9000/services/user